<script setup lang="ts">
import { Avatar, Breadcrumb, Card, Divider, Tag } from '@pixelium/web-vue'
import MobileToc from './MobileToc.vue'
type Heading = { slug: string; text: string; depth: number }
type Related = { id: string; title: string } | null
const props = defineProps<{ post: { title: string; summary: string; category: string; publishedAt: string; updatedAt?: string; readingTime: number; cover: string; coverAlt: string }; headings: Heading[]; previous: Related; next: Related }>()
const breadcrumb=[{label:'首页',href:'/'},{label:props.post.category,href:`/categories/${encodeURIComponent(props.post.category)}/`},{label:'正文'}]
</script>
<template><main id="main" class="article-shell"><article data-pagefind-body><Breadcrumb :options="breadcrumb"/><header class="article-header"><Tag theme="warning" size="small">{{post.category}}</Tag><h1 data-pagefind-meta="title">{{post.title}}</h1><p class="article-summary">{{post.summary}}</p><div class="meta"><span>发布于 {{post.publishedAt}}</span><span v-if="post.updatedAt">更新于 {{post.updatedAt}}</span><span>{{post.readingTime}} MIN READ</span></div></header><MobileToc :headings="headings"/><picture><source :srcset="post.cover.replace(/\.png$/, '.webp')" type="image/webp"><img class="article-cover" :src="post.cover" :alt="post.coverAlt" width="960" height="540"></picture><div class="prose"><slot/></div><Divider :size="2"/><nav class="article-nav" aria-label="文章导航"><Card v-if="previous" bordered><a :href="`/posts/${previous.id}/`"><small>上一篇</small><strong>{{previous.title}}</strong></a></Card><Card v-if="next" bordered><a :href="`/posts/${next.id}/`"><small>下一篇</small><strong>{{next.title}}</strong></a></Card></nav></article><aside class="article-aside"><nav class="toc" aria-label="文章目录"><h2>ON THIS PAGE</h2><div class="toc-links"><a v-for="heading in headings" :key="heading.slug" :href="`#${heading.slug}`">{{heading.text}}</a></div></nav><Divider :size="2"/><div class="author-note"><Avatar shape="square" :size="56" bordered background-color="#ffd166">澈</Avatar><strong>阿澈 / A-CHE</strong><p>产品设计师、业余开发者，关注界面、独立创作和旧游戏。</p></div></aside></main></template>
