<script setup lang="ts">
import { Avatar, Breadcrumb, Card, Divider, Tag } from '@pixelium/web-vue'
import MobileToc from './MobileToc.vue'
type Heading = { slug: string; text: string; depth: number }
type Related = { id: string; title: string } | null
const props = defineProps<{ post: { title: string; summary: string; category: string; publishedAt: string; updatedAt?: string; readingTime: number; cover: string; coverAlt: string }; headings: Heading[]; previous: Related; next: Related }>()
const breadcrumb=[{label:'首页',href:'/'},{label:props.post.category,href:`/categories/${encodeURIComponent(props.post.category)}/`},{label:'正文'}]
</script>
<template><main id="main" class="article-shell"><article data-pagefind-body><div class="article-topline"><Breadcrumb :options="breadcrumb"/><a href="/archive/">返回归档 ↗</a></div><header class="article-header"><div class="article-kicker"><Tag theme="warning" size="small">{{post.category}}</Tag><span>ARTICLE FILE</span></div><h1 data-pagefind-meta="title">{{post.title}}</h1><p class="article-summary">{{post.summary}}</p><dl class="article-meta"><div><dt>发布</dt><dd>{{post.publishedAt}}</dd></div><div v-if="post.updatedAt"><dt>更新</dt><dd>{{post.updatedAt}}</dd></div><div><dt>阅读</dt><dd>{{post.readingTime}} 分钟</dd></div></dl></header><MobileToc :headings="headings"/><figure class="article-figure"><picture><source :srcset="post.cover.replace(/\.png$/, '.webp')" type="image/webp"><img class="article-cover" :src="post.cover" :alt="post.coverAlt" width="960" height="540"></picture><figcaption>{{post.coverAlt}}</figcaption></figure><div class="prose"><slot/></div><Divider :size="2"/><nav class="article-nav" aria-label="文章导航"><Card v-if="previous" bordered><a :href="`/posts/${previous.id}/`"><small>← 上一篇</small><strong>{{previous.title}}</strong></a></Card><Card v-if="next" bordered><a :href="`/posts/${next.id}/`"><small>下一篇 →</small><strong>{{next.title}}</strong></a></Card></nav></article><aside class="article-aside"><nav class="toc" aria-label="文章目录"><div class="pixel-label">ON THIS PAGE</div><div class="toc-links"><a v-for="(heading,index) in headings" :key="heading.slug" :href="`#${heading.slug}`"><span>{{String(index+1).padStart(2,'0')}}</span>{{heading.text}}</a></div></nav><Divider :size="2"/><div class="author-note"><Avatar shape="square" :size="56" bordered background-color="#ffd166">澈</Avatar><div><strong>阿澈 / A-CHE</strong><p>产品设计师、业余开发者，关注界面、独立创作和旧游戏。</p></div></div></aside></main></template>
