<script setup lang="ts">
import { Card, Col, Link, Row, Tag } from '@pixelium/web-vue'
import PixelIcon from './PixelIcon.vue'
type Post = { id:string; title:string; summary:string; category:string; publishedAt:string; readingTime:number; tags:string[]; cover:string; coverAlt:string }
defineProps<{ featured: Post[]; posts: Post[]; topics: { label:string; count:number; href:string }[] }>()
</script>
<template>
  <main id="main">
    <section class="container hero"><div class="hero-copy-block"><div class="eyebrow">个人博客 / 设计 · 代码 · 独立创作</div><h1>在有限网格里，记录<span>无限好奇</span>。</h1><p class="hero-copy">我是阿澈，一名产品设计师和业余开发者。这里存放我对界面、技术与游戏的拆解，也记录那些尚未成为答案的想法。</p><div class="hero-actions"><a class="site-action site-action-primary" href="#latest"><span>开始阅读</span><PixelIcon name="arrow-down" :size="18" /></a><a class="site-action site-action-secondary" href="/about/"><span>关于作者</span><PixelIcon name="external-link" :size="18" /></a></div><dl class="hero-stats"><div><dt>文章</dt><dd>{{ posts.length }}</dd></div><div><dt>主题</dt><dd>{{ topics.length }}</dd></div><div><dt>更新</dt><dd>{{ posts[0]?.publishedAt }}</dd></div></dl></div><div class="pixel-desk" role="img" aria-label="像素风工作台，显示器上打开了一篇新文章"><div class="window"><div class="window-bar"><i></i><i></i><i></i></div><div class="window-content"><div class="window-line"></div><div class="window-line"></div><div class="window-line"></div><div class="window-line"></div></div></div><div class="plant"><span class="leaf"></span><span class="leaf"></span><span class="pot"></span></div><div class="mug"></div><div class="desk-base"></div><span class="desk-caption">WORKSPACE_01</span></div></section>
    <section class="home-band selected-band"><div class="section container"><div class="section-head"><div><div class="pixel-label">SELECTED FILES / 01</div><h2>精选文章</h2></div><Link href="/archive/">查看全部 {{posts.length}} 篇 <PixelIcon name="arrow-right" :size="15" /></Link></div><Row v-if="featured[0]" :gutter="20" align="stretch"><Col :span="{xs:24,sm:24,md:15,lg:15,xl:15}"><Card class="feature-card" bordered><a class="feature-link" :href="`/posts/${featured[0].id}/`"><picture><source :srcset="featured[0].cover.replace(/\.png$/, '.webp')" type="image/webp"><img class="cover-art" :src="featured[0].cover" :alt="featured[0].coverAlt" width="960" height="540"></picture><div class="feature-content"><div class="card-kicker"><Tag theme="warning" size="small">{{featured[0].category}}</Tag><span>FEATURED</span></div><h3>{{featured[0].title}}</h3><p>{{featured[0].summary}}</p><div class="feature-footer"><div class="meta"><span>{{featured[0].publishedAt}}</span><span>{{featured[0].readingTime}} MIN READ</span><span v-if="featured[0].tags[0]">#{{featured[0].tags[0]}}</span></div><span class="feature-open">阅读文章 <PixelIcon name="external-link" :size="17" /></span></div></div></a></Card></Col><Col :span="{xs:24,sm:24,md:9,lg:9,xl:9}"><div class="side-list"><Card v-for="(item,index) in featured.slice(1,3)" :key="item.id" class="side-card" bordered><a :href="`/posts/${item.id}/`"><span class="side-index">0{{index+2}}</span><img class="mini-art" :src="item.cover.replace(/\.png$/, '.webp')" alt="" width="96" height="96"><span><small class="pixel-label">{{item.category}}</small><h3>{{item.title}}</h3><span class="meta">{{item.publishedAt}} · {{item.readingTime}} MIN</span></span></a></Card></div></Col></Row></div></section>
    <section id="latest" class="section container latest-layout"><div><div class="section-head"><div><div class="pixel-label">RECENT LOG / 02</div><h2>最近更新</h2></div></div><div class="post-list"><a v-for="(post,index) in posts.slice(0,6)" :key="post.id" class="post-row" :href="`/posts/${post.id}/`"><span class="post-index">0{{index+1}}</span><span class="post-date">{{post.publishedAt}}</span><span><h3>{{post.title}}</h3><p>{{post.summary}}</p></span><PixelIcon class="arrow" name="external-link" :size="19" /></a></div></div><aside id="topics" class="topic-panel"><div class="pixel-label">TOPIC INDEX</div><h3>按主题探索</h3><div class="topic-links"><a v-for="(topic,index) in topics" :key="topic.href" class="topic-link" :href="topic.href"><small>0{{index+1}}</small><span>{{topic.label}}</span><strong>{{String(topic.count).padStart(2,'0')}}</strong></a></div><a class="topic-all" href="/tags/"><span>浏览全部标签</span><PixelIcon name="arrow-right" :size="18" /></a></aside></section>
  </main>
</template>
