<script setup lang="ts">
import { Button, Card, Col, Divider, Link, Row, Tag } from '@pixelium/web-vue'
type Post = { id:string; title:string; summary:string; category:string; publishedAt:string; readingTime:number; tags:string[]; cover:string; coverAlt:string }
defineProps<{ featured: Post[]; posts: Post[]; topics: { label:string; count:number; href:string }[] }>()
</script>
<template>
  <div class="status-strip"><div class="container"><span><i class="status-dot"></i>ONLINE · 上海 23:42</span><span>本月更新 3 篇 · RSS 可用</span></div></div>
  <main id="main">
    <section class="container hero"><div><div class="eyebrow">个人博客 / 设计 + 代码 + 独立创作</div><h1>在有限网格里，记录<span>无限好奇</span>。</h1><p class="hero-copy">我是阿澈，一名产品设计师和业余开发者。这里存放我对界面、技术与游戏的拆解，也记录那些尚未成为答案的想法。</p><div class="hero-actions"><Button size="large" theme="sakura"><a href="#latest">开始阅读 ↓</a></Button><Button size="large" variant="outline"><a href="#about">认识作者</a></Button></div></div><div class="pixel-desk" role="img" aria-label="像素风工作台，显示器上打开了一篇新文章"><div class="window"><div class="window-bar"><i></i><i></i><i></i></div><div class="window-content"><div class="window-line"></div><div class="window-line"></div><div class="window-line"></div><div class="window-line"></div></div></div><div class="plant"><span class="leaf"></span><span class="leaf"></span><span class="pot"></span></div><div class="mug"></div><div class="desk-base"></div></div></section>
    <Divider :size="2" :margin="0" />
    <section class="section container"><div class="section-head"><div><div class="pixel-label">SELECTED FILES</div><h2>精选文章</h2></div><Link href="/archive/">查看全部 {{posts.length}} 篇</Link></div><Row v-if="featured[0]" :gutter="24" align="stretch"><Col :span="{xs:24,sm:24,md:14,lg:14,xl:14}"><Card class="feature-card" bordered><picture><source :srcset="featured[0].cover.replace(/\.png$/, '.webp')" type="image/webp"><img class="cover-art" :src="featured[0].cover" :alt="featured[0].coverAlt" width="960" height="540"></picture><div class="feature-content"><Tag theme="warning" size="small">{{featured[0].category}}</Tag><h3><a :href="`/posts/${featured[0].id}/`">{{featured[0].title}}</a></h3><p>{{featured[0].summary}}</p><div class="meta"><span>{{featured[0].publishedAt}}</span><span>{{featured[0].readingTime}} MIN READ</span><span v-if="featured[0].tags[0]">#{{featured[0].tags[0]}}</span></div></div></Card></Col><Col :span="{xs:24,sm:24,md:10,lg:10,xl:10}"><div class="side-list"><Card v-for="item in featured.slice(1,3)" :key="item.id" class="side-card" bordered><a :href="`/posts/${item.id}/`"><img class="mini-art" :src="item.cover.replace(/\.png$/, '.webp')" alt="" width="96" height="96"><span><small class="pixel-label">{{item.category}}</small><h3>{{item.title}}</h3><span class="meta">{{item.publishedAt}} · {{item.readingTime}} MIN</span></span></a></Card></div></Col></Row></section>
    <Divider :size="2" :margin="0" />
    <section id="latest" class="section container latest-layout"><div><div class="section-head"><div><div class="pixel-label">RECENT LOG</div><h2>最近更新</h2></div></div><div class="post-list"><a v-for="post in posts.slice(0,6)" :key="post.id" class="post-row" :href="`/posts/${post.id}/`"><span class="post-date">{{post.publishedAt}}</span><span><h3>{{post.title}}</h3><p>{{post.summary}}</p></span><span class="arrow">→</span></a></div></div><aside id="topics" class="topic-panel"><h3>按主题探索</h3><div class="topic-links"><Button v-for="topic in topics" :key="topic.href" variant="outline" block><a :href="topic.href"><span>{{topic.label}}</span><strong>{{topic.count}}</strong></a></Button></div></aside></section>
  </main>
</template>
